version: '3.7'

services:
  cdk:
    container_name: cdk
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: service:localstack
    volumes:
      - ../:/workspace
      - /Users/Hugo/.ssh:/root/.ssh
#      - /Users/Hugo/.aws:/root/.aws
    environment:
      - AWS_ENDPOINT_URL=http://localhost:4566
  
  localstack:
    container_name: aws-local
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - data:/var/lib/localstack:rw
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  data:
